spring:
  datasource:
    url: jdbc:mysql://gg.xsqwe.com:3306/inspinia_admin?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: g123456
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:  # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

            # 配置 mybatis 规则
mybatis: # 指定mybatis 的全局配置文件位置
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml  # 指定sql 映射文件位置
  configuration:    # 指定mybatis 中的全局相关配置项
    map-underscore-to-camel-case: true    # 开启驼峰命名

